#! /bin/sh

# Code to take fixed svg file images, and minify them for inclusion of the web
# pages.  The sources are raw/«name».svg or raw/«name»-fix.svg, and the
# corresponding output is img/«name».svg

svgo -i raw/CIRC01_bb.svg -o img/CIRC01_bb.svg
svgo -i raw/CIRC01_schem-fix.svg -o img/CIRC01_schem.svg

svgo -i raw/CIRC02_bb-fix.svg -o img/CIRC02_bb.svg
svgo -i raw/CIRC02_schem-fix.svg -o img/CIRC02_schem.svg

svgo -i raw/CIRC03_bb-fix.svg -o img/CIRC03_bb.svg
svgo -i raw/CIRC03_schem-fix.svg -o img/CIRC03_schem.svg

# svgo -i raw/CIRC12_bb.svg     -o img/CIRC12_bb.svg
# svgo -i raw/CIRC12a_schem.svg -o img/CIRC12a_schem.svg
# svgo -i raw/CIRC12c_schem.svg -o img/CIRC12c_schem.svg
# svgo -i raw/CIRC15_bb.svg     -o img/CIRC15_bb.svg
# svgo -i raw/CIRC15_schem.svg  -o img/CIRC15_schem.svg
